Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("payments/",include("payments.urls")),
    path("users/",include("users.urls")),



    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
	path("",views.index,name = "index"),
	path("convert/",views.convert,name = "user_convert"),
	path("api-convert/",views.api_convert,name = "api_convert"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"


urlpatterns = [
	path("login/",views.userlogin,name = "login"),
	path("logout/",views.userlogout,name = "logout"),
	path("register/",views.userregister,name = "register"),
	path("dashboard/",views.profile,name = "profile"),
	path("delete/",views.delete,name = "delete"),
	path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError

def validate_file_size(value):
    filesize= value.size
    if filesize > 10485760:
        raise ValidationError(f"The maximum file size that can be uploaded is 10mb but found {round(filesize*0.00000095367432,1)}mb")
    else:
        return value


def validate_file_extension(value):
	return FileExtensionValidator(["png"])(value)


class UploadFileForm(forms.Form):
    file = forms.ImageField(validators=[validate_file_extension,validate_file_size])

core/views.py
from django.http import HttpResponse,HttpResponseNotFound
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


import os 

from payments.models import Customer
from core.forms import UploadFileForm

import io
from PIL import Image


def index(request):
    return render(request,"core/index.html",{"title":"Home Page"})


@login_required
def convert(request):
    form = UploadFileForm()
    return render(request,"core/user_convert.html",{"form":form})


@csrf_exempt
def api_convert(request):
    if request.method == 'POST':
        token = request.POST.get("token")
        if token:
            try:             
                c = Customer.objects.get(token = token)
                if c.balance >= 1:
                    form = UploadFileForm(request.POST, request.FILES)
                    if form.is_valid():
                        image = form.cleaned_data['file']
                        image = Image.open(image).convert('RGB')
                        with io.BytesIO() as f:
                            image.save(f, format='JPEG',optimize=True,quality=70)
                            imi = f.getvalue()
                        response  =  HttpResponse(imi,content_type="image/jpeg")
                        response['Content-Disposition'] = f'attachment; filename=image.jpg'
                        c.balance -= 1
                        c.save()
                        return response
                    else:
                        error  = ''
                        for i in form.errors.as_data()['file']:
                            for j in i:
                                error += j
                        return HttpResponseNotFound(error)
                else:
                    return HttpResponseNotFound("Low Balance Kindly Recharge")
            except:
                return HttpResponseNotFound("No Key Found")
        else:
            return HttpResponseNotFound("Wrong Key")
    else:
        return HttpResponseNotFound("Method Not allowed")

core/templates/core/base.html
{% extends "core/base1.html" %}


{% block content1 %}
<div style="margin-top: 120px!important; margin-bottom: 50px;">
  <div class="container">

	{% if messages %}
	<div class="messages m-auto card1">
	  {% for message in messages %}
	    <div class="alert alert-warning alert-dismissible fade show" role="alert">
	      {{ message }}
	      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	        <span aria-hidden="true">&times;</span>
	      </button>
	    </div>
	  {% endfor %}
	</div>
	{% endif %}

    {% block content %}

    {% endblock %}
  </div>  
</div>



{% endblock %}

core/templates/core/base1.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	{% block title %}
	{% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
      integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk="
      crossorigin="anonymous"/>

	<link rel="stylesheet" type="text/css" href="{% static 'core/css/base.css' %}">
</head>
<body>

<nav id="header" class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container">
    
  
  <a class="logo" href="{% url 'core:index' %}">Easy Jpg</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto pt-1">
      <li class="nav-item ml-2">
        <a class="nav-link nav-menu" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ml-2">
        <a class="nav-link nav-menu" href="{% url 'core:index' %}#pricing">Pricing</a>
      </li>

      {% if request.user.is_authenticated %}
      <li class="nav-item ml-2">
        <a class="nav-link nav-menu" href="{% url 'users:logout' %}">Logout</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'users:profile' %}" class="get-started-btn scrollto">Dashboard</a>
      </li>
      {% else %}
      <li class="nav-item ml-2">
        <a class="nav-link nav-menu" href="{% url 'users:login' %}">Login</a>
      </li>

      <li class="nav-item">
        <a href="{% url 'users:register' %}" class="get-started-btn scrollto">Register</a>
      </li>
      {% endif %}


    </ul>
  </div>

  </div>
</nav>


{% block content1 %}

{% endblock %}

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="container py-4 text-center">
          &copy; Copyright <strong><span>Easy Pdf</span></strong>. All Rights Reserved
    </div>
  </footer><!-- End Footer -->

{% block javascript %}
{% endblock %}


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/index.html
{% extends "core/base1.html" %}
{% load static %}
{% block title %}
<title>Index</title>
<link rel="stylesheet" type="text/css" href="{% static 'core/css/index.css' %}">
{% endblock %}

{% block content1 %}


  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center mt-5">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
      <div class="row justify-content-center">
        <div class="col-xl-7 col-lg-9 text-center">
          <h1>Png To Jpg Optimizer Saas & Rest Api</h1>
          <h2>Built with django python and stripe payments</h2>
        </div>
      </div>
      <div class="text-center">
        <a href="{% url 'users:register' %}" class="btn-get-started scrollto">Register Now</a>
      </div>

      <div class="row icon-boxes">
        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
          <div class="icon-box text-center">
            <div class="icon"><i class="fas fa-layer-group"></i></div>
            <h4 class="title"><a href="">Lorem Ipsum</a></h4>
            <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="300">
          <div class="icon-box text-center">
            <div class="icon"><i class="fas fa-palette"></i></div>
            <h4 class="title"><a href="">Sed ut perspiciatis</a></h4>
            <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="400">
          <div class="icon-box text-center">
            <div class="icon"><i class="fas fa-terminal"></i></div>
            <h4 class="title"><a href="">Magni Dolores</a></h4>
            <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="500">
          <div class="icon-box text-center">
            <div class="icon"><i class="fas fa-fingerprint"></i></div>
            <h4 class="title"><a href="">Nemo Enim</a></h4>
            <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis</p>
          </div>
        </div>

      </div>
    </div>
  </section><!-- End Hero -->

  <main id="main">



    <!-- ======= Pricing Section ======= -->
    <section id="pricing" class="pricing">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Pricing</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="row">

          <div class="col-lg-4 col-md-6" data-aos="zoom-im" data-aos-delay="100">
            <div class="box">
              <h3>Free</h3>
              <h4><sup>$</sup>0<span></span></h4>
              <ul>
                <li>Get 50 lifetime points</li>
                <li>Nec feugiat nisl</li>
                <li>Nulla at volutpat dola</li>
                <li class="na">Pharetra massa</li>
                <li class="na">Massa ultricies mi</li>
              </ul>
              <div class="btn-wrap">
                <a href="#" class="btn-buy">Buy Now</a>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mt-4 mt-md-0" data-aos="zoom-in" data-aos-delay="100">
            <div class="box featured">
              <h3>Business</h3>
              <h4><sup>$</sup>100<span></span></h4>
              <ul>
                <li>Get Additional 1000 points</li>
                <li>Nec feugiat nisl</li>
                <li>Nulla at volutpat dola</li>
                <li>Pharetra massa</li>
                <li class="na">Massa ultricies mi</li>
              </ul>
              <div class="btn-wrap">
                <a href="#" class="btn-buy">Buy Now</a>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mt-4 mt-lg-0" data-aos="zoom-in" data-aos-delay="100">
            <div class="box">
              <h3>Developer</h3>
              <h4><sup>$</sup>10<span></span></h4>
              <ul>
                <li>Get additional 100 points</li>
                <li>Nec feugiat nisl</li>
                <li>Nulla at volutpat dola</li>
                <li>Pharetra massa</li>
                <li>Massa ultricies mi</li>
              </ul>
              <div class="btn-wrap">
                <a href="#" class="btn-buy">Buy Now</a>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Pricing Section -->


  </main><!-- End #main -->


{% endblock %}

core/templates/core/user_convert.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
<title>Convert</title>
{% endblock %}

{% block content %}
	<div class="card m-auto shadow p-3 mb-5 bg-white rounded">
		<h1 class="mt-3 text-center">Upload Png File</h1>
	  <div class="card-body">
		  <div class="form-group">
		    <label for="exampleInputEmail1">Your Token</label>
		    <input type="text" class="form-control" name="token" id="exampleInputEmail1" disabled="true" value="{{ request.user.customer.token }}">
		  </div>

		<form method="post" action="{% url 'core:api_convert' %}" enctype="multipart/form-data">
			<input type="hidden" name="token"  value="{{ request.user.customer.token }}">
		    {{ form|crispy }}
		    <input class="btn btn-primary btn-block" type="submit" value="Submit">
		</form>
	  </div>
	</div>
{% endblock %}