Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("payments/",include("payments.urls")),
    path("users/",include("users.urls")),



    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
	path("",views.index,name = "index"),
	path("convert/",views.convert,name = "user_convert"),
	path("api-convert/",views.api_convert,name = "api_convert"),
]

payments/urls.py
from django.urls import path
from . import views

app_name = "payments"

urlpatterns = [
	path("add/",views.add,name = "add"),
	path("success/<str:session_id>/",views.success,name = "success"),
	path("fail/",views.fail,name = "fail"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"


urlpatterns = [
	path("login/",views.userlogin,name = "login"),
	path("logout/",views.userlogout,name = "logout"),
	path("register/",views.userregister,name = "register"),
	path("dashboard/",views.profile,name = "profile"),
	path("delete/",views.delete,name = "delete"),
	path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser


class MyUser(AbstractUser):
	email = models.EmailField(unique = True)
	is_verified = models.BooleanField(default = False)
	EMAIL_FIELD = 'email'

users/forms.py
from users.models import MyUser
from django.contrib.auth.forms import UserCreationForm

from django import forms

class LoginForm(forms.Form):
	email = forms.EmailField()
	password = forms.CharField(widget=forms.PasswordInput())


class PasswordValidationForm(forms.Form):
	password = forms.CharField(widget=forms.PasswordInput())



class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ("username","email")

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth import login,logout,authenticate
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.urls import reverse


from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes,force_text
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode


from users.models import MyUser
from users.forms import LoginForm,PasswordValidationForm,CustomUserCreationForm
from users.tokens import account_activation_token

def userlogin(request):

	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid():
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			try:
				user = MyUser.objects.get(email = email)
				user = authenticate(request,username = user.username,password = password)
				if user:
					if not user.is_verified:
						send_activation_email(request,user)
						messages.error(request, 'Email not verified!. Verification email sended!')
					else:
						login(request,user)
						return redirect("users:profile")
				else:
					messages.error(request, 'Invalid Email/Password.')
			except MyUser.DoesNotExist:
				messages.error(request, 'Invalid Email/Password.')
	else:
		form = LoginForm()

	return render(request,"users/login.html",{"form":form})



def userregister(request):
	if request.method == "POST":
		form = CustomUserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			send_activation_email(request,user)
			messages.success(request, 'Account has been created but you need to verify your email.check inbox')
			return redirect("users:login")
	else:
		form = CustomUserCreationForm()
	return render(request,"users/register.html",{"form":form})



@login_required
def delete(request):
	if request.method == "POST":
		form = PasswordValidationForm(request.POST)

		if form.is_valid():
			password = form.cleaned_data['password']
			user = request.user
			user = authenticate(request,username = user.username,password = password)
			if user:
				user.delete()
				messages.success(request, 'Account has been deleted')
				return redirect("users:login")
			else:
				messages.error(request, 'Invalid Password')
	else:
		form = PasswordValidationForm()
	return render(request,"users/delete.html",{"form":form})


@login_required
def profile(request):
	return render(request,"users/profile.html")


@login_required
def userlogout(request):
	logout(request)
	messages.success(request, 'User has been logged out')
	return redirect("users:login")


def activate(request,uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = MyUser.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, MyUser.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_verified = True
        user.save()
        messages.success(request, ('Your account have been confirmed.'))
    else:
        messages.warning(request, ('The confirmation link was invalid, possibly because it has already been used.'))
    return redirect('users:login')



def send_activation_email(request,user):
	site = get_current_site(request).domain
	uid = urlsafe_base64_encode(force_bytes(user.pk))
	token = account_activation_token.make_token(user)
	url = "http://" + site + reverse("users:activate",args = (uid,token))

	send_mail('Easy Jpg Email Verification',f'click here to confirm {url}.','testing@gmail.com',[user.email],fail_silently=False)

users/templates/users/delete.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
<title>Delete Account</title>
{% endblock %}

{% block content %}


	<div class="card m-auto shadow p-3 mb-5 bg-white rounded">
		<h1 class="mt-3 text-center">Delete Account</h1>
	  <div class="card-body">
		<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<input class="btn btn-danger btn-block" type="submit" value="Submit">
		</form>
	  </div>
	</div>

{% endblock %}

users/templates/users/login.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
<title>Login</title>
{% endblock %}

{% block content %}
	<div class="card m-auto shadow p-3 mb-5 bg-white rounded">
		<h1 class="mt-3 text-center">Login Here</h1>
	  <div class="card-body">
		<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<p>Forget Password <a href="{% url 'password_reset' %}">Reset Here</a> </p>
		<input class="btn btn-primary btn-block" type="submit" value="Submit">
		</form>
	  </div>
	</div>

{% endblock %}

users/templates/users/password_reset.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
<title>Password Reset</title>
{% endblock %}

{% block content %}
	<div class="card m-auto shadow p-3 mb-5 bg-white rounded">
		<h1 class="mt-3 text-center">Password Reset</h1>
	  <div class="card-body">
		<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<input class="btn btn-primary btn-block" type="submit" value="Submit">
		</form>
	  </div>
	</div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "core/base.html" %}

{% block title %}
<title>Password Reset Complete</title>
{% endblock %}

{% block content %}
<div class="alert alert-success" role="alert">
  Your password has been set.
</div>
        
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
<title>Password Reset Confirmation</title>
{% endblock %}


{% block content %}

<div class="card m-auto shadow p-3 mb-5 bg-white rounded">
	<h1 class="mt-3 text-center">Set Password</h1>
  <div class="card-body">
	<form method="post">
	{% csrf_token %}
	{{ form|crispy }}
	<input class="btn btn-primary btn-block" type="submit" value="Submit">
	</form>
  </div>
</div>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "core/base.html" %}

{% block title %}
<title>Password Reset Done</title>
{% endblock %}

{% block content %}
<div class="alert alert-success" role="alert">
  An email has been sent with instructions to reset your password
</div>
        
{% endblock content %}

users/templates/users/profile.html
{% extends "core/base.html" %}

{% block title %}
<title>Dashboard</title>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/themes/prism-okaidia.min.css">

{% endblock %}


{% block content %}


<div class="card m-auto shadow p-3 mb-5 bg-white rounded">
	<h1 class="mt-3 text-center">Your Balance : {{ request.user.customer.balance }}</h1>
  <div class="card-body">
  <div class="form-group">
    <label for="exampleInputEmail1">Your Token</label>
    <input type="text" class="form-control" id="exampleInputEmail1" disabled="true" value="{{ request.user.customer.token }}">
  </div>
  </div>
</div>

  <div class="card m-auto shadow mb-5 bg-white rounded">
    <div class="card-body">
      <div class="row mb-3">
        <div class="col text-center">
          <a href="{% url 'core:user_convert' %}" type="button" class="btn btn-success btn-block">Convert To Jpg</a>
        </div>
        <div class="col text-center">
          <a href="#" type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#exampleModal">Using Api</a>
        </div>
      </div>
      <div class="row">
        <div class="col text-center">
          <a href="{% url 'payments:add' %}" type="button" class="btn btn-dark btn-block">Add Balance</a>
        </div>
        <div class="col text-center">
          <a href="{% url 'users:delete' %}" type="button" class="btn btn-danger btn-block">Delete Account</a>
        </div>
      </div>
    </div>
  </div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">How to use Api</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="lead">In this demo, i will be using python request library to send http request to the server and convert html document to pdf. here is the program.</p>
        
            <pre class=" language-python">
              <code class="language-python">
import requests

token = "{{request.user.customer.token}}"

data = {'token':token}
files = {'file': open('image.png','rb')}

r = requests.post("http://pngtojpg.herokuapp.com/api-convert/",files = files,data = data)

if r.status_code == 200:
  with open("index.jpg","wb") as file:
    file.write(r.content)</code>
            </pre>  
</div>

    </div>
  </div>
</div>

{% endblock %}


{% block javascript %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/prism.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/components/prism-python.min.js
"></script>
{% endblock %}

users/templates/users/register.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
<title>Register</title>
{% endblock %}

{% block content %}
	<div class="card m-auto shadow p-3 mb-5 bg-white rounded">
		<h1 class="mt-3 text-center">Register Here</h1>
	  <div class="card-body">
		<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<input class="btn btn-primary btn-block" type="submit" value="Submit">
		</form>
	  </div>
	</div>




{% endblock %}